# Generated by Django 3.0.4 on 2020-05-05 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(default='0', max_length=128)),
            ],
            options={
                'verbose_name': 'УДК',
                'verbose_name_plural': 'УДК',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udc_id', models.CharField(max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('parent', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Book.Category')),
            ],
            options={
                'verbose_name': 'Категорий',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=512, verbose_name='Название')),
                ('author', models.CharField(default='', max_length=512, verbose_name='Автор')),
                ('isbn', models.CharField(default='', max_length=512)),
                ('key_words', models.TextField(default='', verbose_name='Ключевые слова')),
                ('img', models.ImageField(null=True, upload_to='img/books', verbose_name='Обложка(Фото)')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('used', models.IntegerField(default=0, verbose_name='Использовано')),
                ('e_book', models.BooleanField(default=False, verbose_name='Электроная_версия')),
                ('file', models.FileField(blank=True, null=True, upload_to='file/e_books', verbose_name='Файл')),
                ('printed_book', models.BooleanField(default=False, verbose_name='Печатная версия')),
                ('special_books', models.BooleanField(default=False, verbose_name='Редкая книга')),
                ('work_book', models.BooleanField(default=False, verbose_name='Учебное пособие')),
                ('date_pub', models.DateField(null=True, verbose_name='Опубликовано')),
                ('date_get', models.DateField(null=True, verbose_name='Получено')),
                ('created', models.DateField(auto_now_add=True)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.Faculty', verbose_name='Факультет')),
                ('udc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='УДК', to='Book.Category')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Книгу',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
