# Generated by Django 3.0.4 on 2020-05-27 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='udc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='УДК', to='book.Category', to_field='udc_id'),
        ),
        migrations.AlterField(
            model_name='category',
            name='udc_id',
            field=models.CharField(default=' ', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
