# Generated by Django 3.0.4 on 2020-09-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_real_time_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='book',
            name='real_time_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во книги на данный момент'),
        ),
        migrations.AlterField(
            model_name='book',
            name='used',
            field=models.PositiveIntegerField(default=0, verbose_name='Использовано'),
        ),
    ]
