# Generated by Django 3.0.7 on 2020-11-13 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
        ('book', '0005_auto_20200901_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.Faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='book',
            name='key_words',
            field=models.TextField(blank=True, default='', verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='book',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University', verbose_name='Университет'),
        ),
    ]
