# Generated by Django 3.0.7 on 2020-11-19 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20201120_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='udc_new',
            field=models.ForeignKey(help_text='Универасальная десятичная классификация(просим заполнять эту таблицу)', null=True, on_delete=django.db.models.deletion.CASCADE, to='book.UDC', verbose_name='УДК'),
        ),
        migrations.AlterField(
            model_name='book',
            name='udc',
            field=models.ForeignKey(help_text='Временно', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='УДК', to='book.Category', to_field='udc_id', verbose_name='УДК'),
        ),
    ]
