# Generated by Django 3.2.6 on 2021-08-28 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0029_auto_20210824_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='udc',
            field=models.ForeignKey(blank=True, help_text='Временно', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='УДК', to='book.category', verbose_name='УДК'),
        ),
        migrations.AlterField(
            model_name='book',
            name='udc_new',
            field=models.ForeignKey(blank=True, help_text='Универасальная десятичная классификация', null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.udc', verbose_name='УДК*'),
        ),
    ]
