# Generated by Django 3.2.6 on 2021-08-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0030_auto_20210828_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_get',
            field=models.DateField(blank=True, null=True, verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/books', verbose_name='Обложка(Фото)'),
        ),
    ]
