# Generated by Django 3.0.7 on 2020-11-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_auto_20201113_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_pub',
            field=models.DateField(null=True, verbose_name='Год издания'),
        ),
    ]
