# Generated by Django 3.0.7 on 2020-11-19 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0009_auto_20201119_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn2',
            field=models.CharField(blank=True, help_text='Международный стандартный номер книги', max_length=20, verbose_name='ISBN 2'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Language'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_initial',
            field=models.CharField(blank=True, max_length=10, verbose_name='Инициал'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_get',
            field=models.DateField(null=True, verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='first_initial',
            field=models.CharField(blank=True, max_length=10, verbose_name='Инициал'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
    ]
