# Generated by Django 3.0.7 on 2020-11-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0010_auto_20201120_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='alias',
        ),
        migrations.AlterField(
            model_name='author',
            name='first_initial',
            field=models.CharField(blank=True, max_length=10, verbose_name='Инициалы'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='first_initial',
            field=models.CharField(blank=True, max_length=10, verbose_name='Инициалы'),
        ),
    ]
