# Generated by Django 3.0.7 on 2020-11-19 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0012_auto_20201120_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AlterField(
            model_name='book',
            name='crossref',
            field=models.ManyToManyField(blank=True, related_name='_book_crossref_+', to='Book.Book', verbose_name='Связанные публикации '),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Language', verbose_name='Язык'),
        ),
    ]
