# Generated by Django 3.0.7 on 2020-11-19 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0014_auto_20201120_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='udc_new',
            field=models.ForeignKey(help_text='Универасальная десятичная классификация(просим заполнять эту таблицу)', null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.UDC', verbose_name='УДК*'),
        ),
    ]
