# Generated by Django 3.0.7 on 2020-11-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0016_auto_20201126_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(null=True, verbose_name='Дата издания'),
        ),
    ]
