# Generated by Django 3.0.7 on 2020-11-25 19:33

from django.db import migrations
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0017_auto_20201126_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=partial_date.fields.PartialDateField(null=True, verbose_name='Дата издания'),
        ),
    ]
