# Generated by Django 3.0.7 on 2020-11-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0018_auto_20201126_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inventory_number',
            field=models.CharField(blank=True, help_text='Инвертизационные номера, разделенные запятыми или двойным дефисом', max_length=100, verbose_name='Invertory Number'),
        ),
    ]
