# Generated by Django 3.0.7 on 2020-11-30 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0019_book_inventory_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='address',
            field=models.CharField(blank=True, help_text='Адрес издателя', max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='book',
            name='inventory_number',
            field=models.CharField(blank=True, help_text='Инвертизационные номера, разделенные запятыми или двойным дефисом', max_length=100, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='book',
            name='udc',
            field=models.ForeignKey(help_text='Временно', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='УДК', to='Book.Category', verbose_name='УДК'),
        ),
        migrations.AlterField(
            model_name='udc',
            name='name',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='udc',
            name='udc',
            field=models.CharField(max_length=64, verbose_name='Код УДК'),
        ),
        migrations.CreateModel(
            name='UDCImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/udc', verbose_name='Иконка')),
                ('udc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Book.UDC')),
            ],
        ),
    ]
