# Generated by Django 3.0.7 on 2020-11-29 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0020_auto_20201126_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='udc',
            field=models.ForeignKey(help_text='Временно', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='УДК', to='Book.Category', verbose_name='УДК'),
        ),
    ]
