# Generated by Django 3.0.7 on 2020-11-29 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0021_auto_20201129_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='UDCImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/udc', verbose_name='Иконка')),
                ('udc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Book.UDC')),
            ],
        ),
    ]
