# Generated by Django 3.0.7 on 2020-12-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0021_auto_20201202_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyrightmark',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Аббревиатура/код объекта'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Аббревиатура/код объекта'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Аббревиатура/код объекта'),
        ),
        migrations.AlterField(
            model_name='language',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Аббревиатура/код объекта'),
        ),
        migrations.AlterField(
            model_name='librarystorage',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Аббревиатура/код объекта'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Аббревиатура/код объекта'),
        ),
    ]
