# Generated by Django 3.0 on 2020-12-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0021_auto_20201202_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='udc',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='udc',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
