# Generated by Django 3.0.7 on 2020-11-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0022_udcimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udc',
            name='name',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='udc',
            name='udc',
            field=models.CharField(max_length=64, verbose_name='Код УДК'),
        ),
    ]
