# Generated by Django 3.0 on 2020-12-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0023_auto_20201221_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udc',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Название'),
        ),
    ]
