# Generated by Django 3.0.7 on 2020-11-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0023_auto_20201130_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='address',
            field=models.CharField(blank=True, help_text='Адрес издателя', max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='book',
            name='inventory_number',
            field=models.CharField(blank=True, help_text='Инвертизационные номера, разделенные запятыми или двойным дефисом', max_length=100, verbose_name='Инвентарный номер'),
        ),
    ]
