# Generated by Django 3.0 on 2021-01-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0025_auto_20210124_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booktitle',
            field=models.CharField(blank=True, help_text='Название книги, если цитируется только ее часть', max_length=512, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, help_text='Издание книги', max_length=512, verbose_name='Издание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='organization',
            field=models.CharField(blank=True, help_text='Спонсор конференции', max_length=100, verbose_name='Организция'),
        ),
        migrations.AlterField(
            model_name='book',
            name='school',
            field=models.CharField(blank=True, help_text='Школа, в которой была написана диссертация', max_length=100, verbose_name='Школа'),
        ),
    ]
