version: "3.8"

services:
#  nginx:
#    image: nginx:1.19.6
#    ports:
#      - 80:80
#    restart: always
#    volumes:
#      - ./nginx.conf:/etc/nginx/sites-available/autolib.conf
#      - ./static:/static
#    depends_on:
#      - web

  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - /private/var/lib/postgresql/data:/var/lib/postgresql/data
      - .:/code


  web:
    restart: always
    image: autolib:latest
    build: .
    command: sh run.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
