version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - /private/var/lib/postgresql/data:/var/lib/postgresql/data
      - .:/code
    cpu_count: 10
    cpuset: "0-10"
    cpus: 10.00


  web:
    build: .
    command: sh run.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
    cpu_count: 15
    cpuset: "20-35"
    cpus: 10.00
