# Generated by Django 3.0.4 on 2020-03-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time_of_get_book',
        ),
    ]
