# Generated by Django 3.0.4 on 2020-03-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_user_time_of_get_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Ф.И.О.',
            new_name='full_name',
        ),
    ]
