# Generated by Django 3.0.4 on 2020-07-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200723_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kafedra',
            field=models.TextField(default='nll', verbose_name='Кафедра'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.TextField(default='nll', verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
