# Generated by Django 3.0.7 on 2020-11-19 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200915_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='img/users', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group_name',
            field=models.TextField(blank=True, null=True, verbose_name='Номер группы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kafedra',
            field=models.TextField(blank=True, null=True, verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_serial_id',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Серийный номер пасспорта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.TextField(blank=True, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel_num',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Номер телефона'),
        ),
    ]
