# Generated by Django 3.0 on 2020-12-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20201207_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
    ]
