# Generated by Django 3.0 on 2020-12-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_profile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='application_id',
            field=models.CharField(blank=True, help_text='ID пользовалтеля для интеграции с Autolib', max_length=36, null=True, verbose_name='ID пользователя в другом приложении'),
        ),
    ]
