# Generated by Django 3.0 on 2020-12-14 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_profile_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel_num',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Номер телефона'),
        ),
    ]
