# Generated by Django 3.2.6 on 2021-08-27 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0003_auto_20210824_2218'),
        ('book', '0029_auto_20210824_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(max_length=8)),
                ('tag_id', models.CharField(max_length=64)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.book')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.university')),
            ],
        ),
    ]
