# Generated by Django 3.2.6 on 2021-08-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='tag_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
