# Generated by Django 3.0.4 on 2020-08-26 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200723_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_of_order',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='time_of_get',
            field=models.DateTimeField(),
        ),
    ]
