# Generated by Django 3.0.4 on 2020-08-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200826_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_of_get',
            field=models.DateTimeField(verbose_name='Время полчения книги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_of_order',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время заказа'),
        ),
    ]
