# Generated by Django 3.0.4 on 2020-08-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200828_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='retrieved',
            field=models.BooleanField(default=False, verbose_name='Возвращен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
