# Generated by Django 3.0.7 on 2020-10-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20201018_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_of_pass',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время возвращения книги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_of_take_away',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время унесения книги'),
        ),
    ]
