# Generated by Django 3.2.6 on 2021-08-29 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_of_get',
        ),
    ]
