# Generated by Django 3.0.4 on 2020-03-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Дата получения',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='Дата публикации',
            field=models.DateTimeField(),
        ),
    ]
