# Generated by Django 3.0.4 on 2020-03-26 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20200326_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created',
        ),
        migrations.RemoveField(
            model_name='book',
            name='Дата получения',
        ),
        migrations.AddField(
            model_name='book',
            name='date_get',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
