# Generated by Django 3.0.4 on 2020-08-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_auto_20200727_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='real_time_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во книги на данный момент'),
        ),
    ]
