# Generated by Django 3.0.4 on 2020-03-26 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_auto_20200326_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='Автор',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='quantity',
            new_name='Количество',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='used',
            new_name='Количество использований',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='Название Книги',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='img',
            new_name='Обложка(Фото)',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Спец книги',
            new_name='Спец. книга',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='udc',
            new_name='УДК',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='university',
            new_name='Университет',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='file',
            new_name='Файл(Э-Книга)',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='faculty',
            new_name='Факультет',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date_get',
        ),
        migrations.AddField(
            model_name='book',
            name='Дата получения',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
