# Generated by Django 3.0.4 on 2020-03-26 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_auto_20200326_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Название Книги',
            new_name='Название',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Дата получения',
            new_name='Получение',
        ),
        migrations.RemoveField(
            model_name='book',
            name='Дата публикации',
        ),
        migrations.AddField(
            model_name='book',
            name='Публикация',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
