# Generated by Django 3.0.4 on 2020-03-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_auto_20200326_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Количество использований',
            new_name='Использовано',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Файл(Э-Книга)',
            new_name='Файл(Книга)',
        ),
    ]
