# Generated by Django 3.0.4 on 2020-03-26 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0007_auto_20200326_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Получение',
            new_name='Опубликовано',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Публикация',
            new_name='Получено',
        ),
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
