# Generated by Django 3.0.4 on 2020-03-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0009_auto_20200327_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Спец. книга',
            new_name='Редкая книга',
        ),
    ]
