# Generated by Django 3.0.4 on 2020-03-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0010_auto_20200328_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Печатная версия',
            new_name='Печатная_версия',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Редкая книга',
            new_name='Редкая_книга',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Учебное пособие',
            new_name='Учебное_пособие',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Файл(Книга)',
            new_name='Файл',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='ключевые слова',
            new_name='ключевые_слова',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', max_length=512),
        ),
    ]
