# Generated by Django 3.0.4 on 2020-03-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0011_auto_20200331_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Электроная версия',
            new_name='Электроная_версия',
        ),
    ]
