# Generated by Django 3.0.4 on 2020-04-01 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0001_initial'),
        ('Book', '0012_auto_20200331_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Использовано',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='Количество',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='Обложка(Фото)',
            field=models.ImageField(null=True, upload_to='img/books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Опубликовано',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Получено',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Рейтинг',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='Факультет',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='University.Faculty'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Цена',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ALL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=512)),
                ('Автор', models.CharField(max_length=512)),
                ('isbn', models.CharField(default='', max_length=512)),
                ('ключевые_слова', models.TextField(default='')),
                ('Обложка(Фото)', models.ImageField(upload_to='img/books')),
                ('Электроная_версия', models.BooleanField(default=False)),
                ('Файл', models.FileField(blank=True, null=True, upload_to='file/e_books')),
                ('УДК', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.Category')),
            ],
        ),
    ]
