# Generated by Django 3.0.4 on 2020-04-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0013_auto_20200402_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all',
            name='isbn',
        ),
    ]
