# Generated by Django 3.0.4 on 2020-04-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0014_remove_all_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all',
            options={'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AddField(
            model_name='all',
            name='Опубликовано',
            field=models.DateField(null=True),
        ),
        migrations.AddConstraint(
            model_name='all',
            constraint=models.UniqueConstraint(fields=('Название', 'Автор', 'Опубликовано'), name='allbooks'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('Название', 'Автор', 'Опубликовано'), name='book'),
        ),
    ]
