# Generated by Django 3.0.4 on 2020-04-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0015_auto_20200402_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all',
            options={'verbose_name': 'Книгу', 'verbose_name_plural': 'Все Книги'},
        ),
        migrations.RemoveConstraint(
            model_name='all',
            name='allbooks',
        ),
        migrations.AddConstraint(
            model_name='all',
            constraint=models.UniqueConstraint(fields=('id', 'Название', 'Автор', 'Опубликовано'), name='allbooks'),
        ),
    ]
