# Generated by Django 3.0.4 on 2020-04-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0016_auto_20200403_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tree_id',
        ),
    ]
