# Generated by Django 3.0.4 on 2020-07-14 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Book', '0002_auto_20200527_2345'),
        ('User', '0007_auto_20200714_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_get', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False, verbose_name='Активный')),
                ('done', models.BooleanField(default=False, verbose_name='Заказ получен')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Users')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='BookInUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_get', models.DateTimeField()),
                ('time_of_pass', models.DateTimeField()),
                ('book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Book.Book')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Order.Order')),
            ],
            options={
                'verbose_name': 'Архив пользований книг',
            },
        ),
    ]
