# Generated by Django 3.0.7 on 2020-10-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_auto_20200831_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_of_pass',
            field=models.DateTimeField(null=True, verbose_name='Время возвращения книги'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_of_take_away',
            field=models.DateTimeField(null=True, verbose_name='Время унесения книги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_of_get',
            field=models.DateTimeField(verbose_name='Время получения книги(заказ)'),
        ),
        migrations.DeleteModel(
            name='BookInUse',
        ),
    ]
