# Generated by Django 3.0.4 on 2020-07-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20200716_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email address',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
