# Generated by Django 3.0.4 on 2020-07-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20200716_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group_name',
            field=models.TextField(default='M1-17', verbose_name='Номер группы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_serial_id',
            field=models.CharField(default='AA1234567', max_length=9, verbose_name='Серийный номер пасспорта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.TextField(choices=[('S', 'Student'), ('T', 'Teacher'), ('L', 'Librarian')], default='S'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='tel_num',
            field=models.IntegerField(default=998996779, max_length=9, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.TextField(verbose_name='ФИО'),
        ),
    ]
