# Generated by Django 3.0.4 on 2020-09-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20200723_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='img/users', verbose_name='Аватар'),
        ),
    ]
