# Generated by Django 3.0.4 on 2020-09-15 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0001_initial'),
        ('User', '0013_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Факультет', to='University.Faculty'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group_name',
            field=models.TextField(null=True, verbose_name='Номер группы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kafedra',
            field=models.TextField(null=True, verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.TextField(null=True, verbose_name='Должность'),
        ),
    ]
