# Generated by Django 3.0.4 on 2020-03-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200326_0309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Админ', 'verbose_name_plural': 'Админ'},
        ),
    ]
