# Generated by Django 3.0.4 on 2020-07-23 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20200723_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel_num',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Номер телефона'),
        ),
    ]
