# Generated by Django 3.0.4 on 2020-03-25 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_get', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='BookInUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_get', models.DateTimeField()),
                ('time_of_pass', models.DateTimeField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Order.Order')),
            ],
            options={
                'verbose_name': 'Архив пользований книг',
            },
        ),
    ]
