# Generated by Django 3.0.4 on 2020-04-03 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20200327_0033'),
        ('Book', '0016_auto_20200403_2229'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinuse',
            name='book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Book.Book'),
        ),
        migrations.AddField(
            model_name='bookinuse',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Book.Book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.User'),
            preserve_default=False,
        ),
    ]
