# Generated by Django 3.0.4 on 2020-04-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20200403_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinuse',
            name='user_id',
        ),
    ]
