# Generated by Django 3.0.4 on 2020-08-28 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Order', '0004_auto_20200826_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinuse',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinuse',
            name='time_of_get',
            field=models.DateTimeField(verbose_name='Время полчения книги'),
        ),
        migrations.AlterField(
            model_name='bookinuse',
            name='time_of_pass',
            field=models.DateTimeField(null=True, verbose_name='Время возврата книги'),
        ),
    ]
